# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mantid\STEM-project\stem_project\interface\interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vertical_Layout = QtWidgets.QVBoxLayout()
        self.vertical_Layout.setObjectName("vertical_Layout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 44, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 44, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(178, 229, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(192, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAutoFillBackground(False)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.code_label = QtWidgets.QLabel(self.frame)
        self.code_label.setObjectName("code_label")
        self.horizontalLayout.addWidget(self.code_label)
        self.function_label = QtWidgets.QLabel(self.frame)
        self.function_label.setObjectName("function_label")
        self.horizontalLayout.addWidget(self.function_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontal_Layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_Layout_2.setObjectName("horizontal_Layout_2")
        self.code_area = QtWidgets.QTextEdit(self.frame)
        self.code_area.setObjectName("code_area")
        self.horizontal_Layout_2.addWidget(self.code_area)
        self.functions_area = QtWidgets.QTextBrowser(self.frame)
        self.functions_area.setObjectName("functions_area")
        self.horizontal_Layout_2.addWidget(self.functions_area)
        self.verticalLayout.addLayout(self.horizontal_Layout_2)
        self.horizontal_Layout_3 = QtWidgets.QHBoxLayout()
        self.horizontal_Layout_3.setObjectName("horizontal_Layout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem3)
        self.SubmitButton = QtWidgets.QPushButton(self.frame)
        self.SubmitButton.setObjectName("SubmitButton")
        self.horizontal_Layout_3.addWidget(self.SubmitButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_Layout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontal_Layout_3)
        self.vertical_Layout_2 = QtWidgets.QVBoxLayout()
        self.vertical_Layout_2.setObjectName("vertical_Layout_2")
        self.message_area_2 = QtWidgets.QLabel(self.frame)
        self.message_area_2.setObjectName("message_area_2")
        self.vertical_Layout_2.addWidget(self.message_area_2)
        self.message_area = QtWidgets.QTextBrowser(self.frame)
        self.message_area.setObjectName("message_area")
        self.vertical_Layout_2.addWidget(self.message_area)
        self.verticalLayout.addLayout(self.vertical_Layout_2)
        self.vertical_Layout.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.vertical_Layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Ctrl_O = QtWidgets.QAction(MainWindow)
        self.actionOpen_Ctrl_O.setObjectName("actionOpen_Ctrl_O")
        self.actionSave_Ctrl_S = QtWidgets.QAction(MainWindow)
        self.actionSave_Ctrl_S.setObjectName("actionSave_Ctrl_S")
        self.actionUndo_Ctrl_Z = QtWidgets.QAction(MainWindow)
        self.actionUndo_Ctrl_Z.setObjectName("actionUndo_Ctrl_Z")
        self.actionRedo_Ctrl_Y = QtWidgets.QAction(MainWindow)
        self.actionRedo_Ctrl_Y.setObjectName("actionRedo_Ctrl_Y")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Interface"))
        self.code_label.setText(_translate("MainWindow", "My Code:"))
        self.function_label.setText(_translate("MainWindow", "Available functions to use:"))
        self.code_area.setStatusTip(_translate("MainWindow", "code box"))
        self.code_area.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"># type your code in here</span></p></body></html>"))
        self.SubmitButton.setToolTip(_translate("MainWindow", "Submit code to check answer"))
        self.SubmitButton.setStatusTip(_translate("MainWindow", "Submit"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.message_area_2.setText(_translate("MainWindow", "Message Returned:"))
        self.actionOpen_Ctrl_O.setText(_translate("MainWindow", "Open         Ctrl+O"))
        self.actionOpen_Ctrl_O.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_Ctrl_S.setText(_translate("MainWindow", "Save           Ctrl+S"))
        self.actionSave_Ctrl_S.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionUndo_Ctrl_Z.setText(_translate("MainWindow", "Undo     Ctrl+Z"))
        self.actionUndo_Ctrl_Z.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo_Ctrl_Y.setText(_translate("MainWindow", "Redo      Ctrl+Y"))
        self.actionRedo_Ctrl_Y.setShortcut(_translate("MainWindow", "Ctrl+Y"))

